"""
Central repository for application styles and tool tips.
"""
from pathlib import Path


class StyleColors:
    
    MAIN_BG = "#273945"
    GROUPBOX_BG = "#34454f" # 34454f, 2f3e47 (darker), 394856 (lighter)
    GROUPBOX_BG_DARK = "#2F3E47"
    INPUT_BG = "#1f2d36"
    INPUT_BORDER = "#0f1e28" # "#f0ad4e"
    INPUT_BORDER_AUTO = "#009900"
    BUTTON_BG = "#476273"
    BUTTON_HOVER = "#2ea2ec"
    BUTTON_PRESSED = "#1F6FA1" # 1c5985
    BUTTON_DISABLED = "#3d5462"
    CHECKBOX_INDICATOR_DISABLED = "#4C88AD"
    TEXT_PRIMARY = "#ffffff"
    TEXT_DISABLED = "#808f99"
    RESULT_MATCH = "#00ff85"    # 009900 (ASV green)
    TEXT_BLACK = "#000000"
    # Plot colors
    PLOT_BG = "#000000"
    PLOT_INTERACTIVE_LINE_COLOR = "#04f5ff"
    PLOT_LINE_COLOR = "#eb70a9"
    PLOT_SPINE_COLOR = "#ffffff"
    PLOT_SPECIMEN_CURRENT_COLOR = "#f5c842"

class StyleDimensions:

    WINDOW_WIDTH = 1000
    WINDOW_HEIGHT = 920
    WINDOW_CONTENTS_MARGIN = 4
    BORDER_RADIUS_LARGE = "8.0px"
    BORDER_RADIUS_SMALL = "4.0px"
    MARGIN = "8px"
    PADDING = "4px"
    FONT_SIZE_NORMAL = "11pt"
    FONT_SIZE_LARGE = "14pt"
    SPINBOX_WIDTH = 100
    GROUPBOX_MARGIN = 4  # Margin for group boxes in the main window
    GRID_LAYOUT_CONTENTS_MARGIN = 8
    GRID_LAYOUT_HSPACING = 60
    GRID_LAYOUT_VSPACING = 10
    COLUMN_LAYOUT_MINIMUM_WIDTH = 460   # Minimum width for column layouts (pattern plot group boxes)
    CHECKBOX_SPACING = "16px"
    RESULT_LABEL_MARGIN = "2px"
    # Horizontal inset between a result chip's edge and its value. Explicit,
    # because it used to be an accident: left-aligned QLabels get a small
    # automatic indent against the aligned edge, and centering the values
    # (2026-08-27) removed it -- the text then hugged the chip edges (field
    # report 2026-08-28). Shared by the default and match (green) chip styles
    # so the pass/fail style swap never resizes the chip.
    RESULT_LABEL_HPAD = "6px"
    SETTINGS_DIALOG_WIDTH = 460
    COMBOBOX_WIDTH = 180
    # Plot dimensions
    PLOT_MINIMUM_HEIGHT = 200
    PLOT_LINE_WIDTH = 1.0
    PLOT_TITLE_FONT_SIZE = 11
    # Scan-direction crop edge indicator. The destination edge of the crop box
    # (e.g. the top edge for a bottom-to-top scan) is drawn solid to stand out
    # from the dashed sides. Adjust these to taste:
    #   - LINE_WIDTH: weight of the emphasized edge (1.0 = same as the dashed sides)
    #   - LINE_STYLE: "solid" (default) or "dashed" to match the rest of the box
    # Color reuses PLOT_INTERACTIVE_LINE_COLOR (the crop box color) above.
    SCAN_DIRECTION_LINE_WIDTH = 2.0
    SCAN_DIRECTION_LINE_STYLE = "solid"


# Single source of truth for the app version (window title, launch banner).
APP_VERSION = "3.4.4"


class StatusText:
    """
    Status-bar wording for microscope states the worker reports from more
    than one site. One constant per state: duplicate literals drifted apart
    (the same FIB-inactive pause read differently at the loop guard and the
    batch boundary), and the operator reads different words as different
    states. This module stays Qt-free so the worker can import it safely.
    """

    CONNECTING = "Connecting to microscope..."
    # The status bar's right-side connection indicator (the Hydra utilities
    # vocabulary -- short, because there is nothing else the app could be
    # connected to; field decision 2026-08-28).
    CONNECTED = "Connected"
    NOT_CONNECTED = "Not connected"
    FIB_BEAM_OFF = "FIB beam is off - waiting for it to turn on..."
    COMM_RETRY = "Microscope communication issue - retrying..."
    FIB_INACTIVE_PAUSED = ("FIB quadrant is not active - monitoring paused "
                           "until the FIB is selected again")
    FIB_ACTIVE_RESUMED = "FIB quadrant active - monitoring resumed"


class WindowText:

    WINDOW_TITLE = f"ATC Monitor {APP_VERSION}"

    WINDOW_INFO_LABEL_1 = ""

    WINDOW_INFO_LABEL_2 = "Click Start to begin monitoring."

    # Catbug status messages shown while a run is active (see information_label_2).
    WINDOW_INFO_MONITORING_ACTIVE = "Monitoring (patterning detected)..."
    WINDOW_INFO_MONITORING_IDLE = "Monitoring (waiting for patterning)..."
    WINDOW_INFO_MONITORING_PAUSED = "Monitoring paused"
    # Shared with the worker's status-bar text: the operator reads the catbug
    # and the bar as one connecting state, so the words must not drift.
    WINDOW_INFO_CONNECTING = StatusText.CONNECTING

    SETTINGS_DIALOG_TITLE = "ATC Monitor Settings"


class ToolTips:

    # Control group box tool tips

    IMAGE_COUNT_RADIOBUTTON = "Select to set the number of RTM images to analyze in a batch."

    TIME_INTERVAL_RADIOBUTTON = "Select to set the number of seconds to acquire RTM images for analysis in a batch.\n" + \
                                "The number of images to acquire is automatically calculated \n" + \
                                "based on the rate of RTM images generated by the microscope."
    
    NUMBER_OF_IMAGES_LABEL = "Number of RTM images to process and analyze in a batch.\n" + \
                             "After analysis, another batch of images is processed.\n" + \
                             "Only applicable if 'Image Count' mode is selected."
    
    ANALYSIS_INTERVAL_LABEL = "Time interval (in seconds) to acquire RTM images for batch analysis.\n" + \
                              "The number of images to acquire is automatically calculated \n" + \
                              "based on the rate of RTM images generated by the microscope.\n" + \
                              "Only applicable if 'Time Interval' mode is selected."
    
    MEAN_PIXEL_SLOPE_THRESHOLD_LABEL = "The threshold value for the slope of the mean pixel values.\n" + \
                                       "Slope values below the threshold meet the passing criteria for stopping FIB patterning."
    
    MATCH_SCORE_THRESHOLD_LABEL = "The threshold value for the image match score.\n" + \
                                  "Match scores below the threshold meet the passing criteria for stopping FIB patterning.\n" + \
                                  "Match scores are derived from comparing the first image to the last image in a batch of images.\n" + \
                                  "Low match scores indicate better matches.\n" + \
                                  "During milling (a dynamic state), the match scores will increase."

    MAXIMUM_PIXELS_THRESHOLD_LABEL = "The threshold for the foreground metric; values at or below it meet the passing criteria for stopping FIB patterning.\n" + \
                                     "For the white-pixel methods this is the percentage of white pixels in the binary image.\n" + \
                                     "For the Top-Hat Foreground Energy method this is the continuous foreground-energy level (~2.5-3.0, not a 0-100% count) -\n" + \
                                     "see the Binarization Method tooltip, and re-check this value whenever you change the method."
    
    CONFIRMATION_ROUNDS_LABEL = "The number of consecutive rounds that must meet the passing criteria \n" + \
                                "before confirming the FIB patterning is complete."
    
    SHOW_RTM_IMAGES_CHECKBOX = "Toggle to show the processed RTM images in the image display area.\n" + \
                               "When unchecked, the analysis view is shown instead: the binary image for the\n" + \
                               "white-pixel methods, or the foreground map for Top-Hat Foreground Energy."
    
    SAVE_DATA_CHECKBOX = "Toggle to save analysis data to a time-stamped Saved_Data folder in the ATC Monitor application folder."

    # Pattern results group box tool tips

    MEAN_SLOPE_CHECKBOX = "Toggle to include mean pixel value slope as a criterion for confirming FIB patterning completion."

    MATCH_SCORE_CHECKBOX = "Toggle to include match score as a criterion for confirming FIB patterning completion."

    PERCENT_PIXELS_CHECKBOX = "Toggle to include the foreground metric (Percent Pixels / Foreground Energy) as a criterion for confirming FIB patterning completion."

    PERCENT_PIXELS_RESULT = "The most recent foreground-metric value for this pattern. A '(stall)' annotation below the value means completion was reached via the stall latch."

    # Settings dialog tool tips

    ACQUISITION_DELAY_SECONDS_LABEL = "The number of seconds to delay before acquiring RTM images for analysis.\n" + \
                                      "The delay is intended to accommodate data processing (may not be necessary)."
    
    PERCENT_DIFFERENCE_THRESHOLD_LABEL = "The percentage drop in mean pixel value that will disengage the results evaluation delay.\n" + \
                                         "If the mean pixel value drops by this percentage, the results evaluation delay is\n" + \
                                         "disengaged and values will be evaluated for stopping FIB patterning."

    GAUSSIAN_BLUR_SIGMA_LABEL = "The sigma value for Gaussian blur applied to RTM images before analysis (background subtraction)."

    APPLY_DILATION_LABEL = "Toggle to apply a morphological dilation operation to the RTM images before analysis."

    THRESHOLD_NUM_CLASSES_LABEL = "The number of classes for multi-Otsu thresholding (binarization).\n" + \
                                  "Applies only to the Brightest Class method; Middle Boundary and Low Boundary\n" + \
                                  "use a fixed 4 classes, and Top-Hat Foreground Energy does not use it."

    BINARIZATION_METHOD_LABEL = "How the foreground is isolated for the completion metric (Percent Pixels / Foreground Energy).\n" + \
                                "The first three freeze one multi-Otsu class boundary captured once (no drift):\n\n" + \
                                "Brightest Class: only the brightest pixels count - can miss faint, slightly gray features.\n" + \
                                "Middle Boundary: balanced capture of faint mid-gray features (default).\n" + \
                                "Low Boundary: most inclusive; captures the most but includes more noise.\n\n" + \
                                "Top-Hat Foreground Energy: a morphological white top-hat (set the Top-Hat Radius)\n" + \
                                "that is agnostic to the background level - it isolates bright, sharply textured\n" + \
                                "features even when the background is dark vs. gray across patterns. It reports a\n" + \
                                "continuous energy (~2-16), not a 0-100% count, so set the Maximum Pixels Threshold to ~2.5-3.0.\n\n" + \
                                "Any change of method shifts the foreground-metric scale, so re-check the Maximum Pixels Threshold."

    TOPHAT_RADIUS_LABEL = "Disk radius (px) for the Top-Hat Foreground Energy method - the largest foreground\n" + \
                          "feature scale to keep. Features smaller than this survive; the local/static background\n" + \
                          "(including a grid bar) is removed. A larger radius captures bigger structures but more background;\n" + \
                          "a smaller radius keeps only fine detail. Used by the Top-Hat metric and by Match on Foreground Map."

    MATCH_ON_FOREGROUND_LABEL = "Compute the match score on the normalized white top-hat foreground map (uses the\n" + \
                                "Top-Hat Radius) instead of the grayscale image. This makes the match score track\n" + \
                                "structural foreground change and ignore background / brightness drift. Works with\n" + \
                                "any binarization method (independent of the foreground metric). The match-score\n" + \
                                "scale differs from grayscale, so re-check the Match Score Threshold when enabling this."

    FOREGROUND_COMPLETION_MODE_LABEL = "How the foreground (Percent Pixels / Foreground Energy) completion criterion decides 'done'.\n\n" + \
                                       "Absolute (threshold): foreground value must fall to or below the Maximum Pixels threshold (original behavior).\n\n" + \
                                       "Absolute + stall latch: Absolute, plus a backstop for exposed static material. The criterion also\n" + \
                                       "completes the pattern when the foreground trace has provably floored above the threshold (e.g. an\n" + \
                                       "exposed grid bar): fallen to or below the Stall Drop Fraction of its running peak and stayed flat\n" + \
                                       "for Stall Window consecutive rounds. Uses the four stall settings below.\n\n" + \
                                       "The default is Absolute + stall latch (Restore Defaults returns to it). A mode change takes\n" + \
                                       "effect on the next Start."

    STALL_WINDOW_LABEL = "Absolute + stall latch mode only: the number of consecutive monitoring rounds the smoothed foreground\n" + \
                         "trace must stay flat before the stall latch can complete the pattern (~95 seconds at the default\n" + \
                         "5-second analysis interval)."

    STALL_DROP_FRACTION_LABEL = "Absolute + stall latch mode only: the smoothed foreground trace must fall to or below this fraction of\n" + \
                                "its running peak before the stall latch can arm (e.g. 0.35 = dropped to 35%). Lower is stricter\n" + \
                                "(more material must be removed before a stall can complete the pattern)."

    STALL_REL_TOLERANCE_LABEL = "Absolute + stall latch mode only: the relative flatness tolerance, as a fraction of the current smoothed\n" + \
                                "foreground value. The trace counts as flat while its variation over the Stall Window stays within the\n" + \
                                "larger of the relative and absolute tolerances."

    STALL_ABS_TOLERANCE_LABEL = "Absolute + stall latch mode only: the absolute flatness tolerance, in foreground-metric units.\n" + \
                                "The trace counts as flat while its variation over the Stall Window stays within the larger of the\n" + \
                                "relative and absolute tolerances; this floor keeps noise near zero from blocking the latch."

    SLOPE_METHOD_LABEL = "The method for calculating the slope of mean pixel values and match scores.\n\n" + \
                         "Gradient: calculates the slope between the last n data points in the batch.\n" + \
                         "Linear Regression: calculates the slope using linear regression between the last n data points in the batch."
    
    NUM_POINTS_FOR_SLOPE_LABEL = "The number of data points to use for calculating the slope of mean pixel values and match scores.\n" + \
                                 "Only applicable if the 'Gradient' method is selected for slope calculation."
    
    LINEAR_REGRESSION_FIT_POINTS_LABEL = "The number of data points to use for calculating the slope of mean pixel values and match scores using linear regression.\n" + \
                                         "Only applicable if the 'Linear Regression' method is selected for slope calculation."
    
    ASPECT_RATIO_THRESHOLD_LABEL = "The threshold for the aspect ratio of the patterns.\n" + \
                                   "If the aspect ratio of the patterns is below this threshold, then pattern monitoring will remain idle.\n" + \
                                   "This is designed to detect stress-relief cut patterns from AutoTEM Cryo, which are often quite narrow."

    MIN_PATTERN_SPLITS_LABEL = "The minimum number of rows and columns the cropped RTM area is divided into\n" + \
                               "for analysis (2 gives a 2x2 grid of four sub-regions). Mean pixel values and\n" + \
                               "match scores are calculated per sub-region, and the highest of each drives the\n" + \
                               "results evaluation. More sub-regions increase sensitivity to small changes in\n" + \
                               "the patterns, but values may then struggle to reach their thresholds."

    TARGET_TILE_SIZE_LABEL = "The target tile size (in pixels) for the RTM sub-regions (e.g., 100x100 pixel tiles).\n" + \
                             "The actual number of sub-regions is calculated based on the size of the crop area, the target tile size, and the minimum number of sub-regions.\n" +\
                             "To reduce analysis sensitivity, increase the target tile size and reduce the minimum sub-region number."

    # Contrast/Brightness Calibration tool tips

    CB_RECALIBRATE_EVERY_SESSION_LABEL = "By default only the first patterning session of a run is calibrated; later sessions\n" + \
                                         "keep that lock (each calibration mills the live pattern for its duration, and later\n" + \
                                         "sessions start from an already-calibrated detector). Enable this to recalibrate at\n" + \
                                         "the start of every patterning session instead. Editable during a run; a change\n" + \
                                         "applies from the next patterning session."

    CB_AUTO_ON_START_LABEL = "Automatically balance detector contrast/brightness once when patterning starts,\n" + \
                             "then hold it static for the rest of the session (so the analysis criteria are not disrupted).\n" + \
                             "If not enabled, you may need to manually optimize the contrast and brightness values of the live RTM data."

    CB_WHITE_LEVEL_LABEL = "The fallback detector full-scale (saturation ceiling, raw pixel value) used to detect clipping.\n" + \
                           "Calibration normally auto-detects this from the imaging bit depth (2^bits - 1, e.g. 255 for\n" + \
                           "8-bit, 65535 for 16-bit); this value is only used when the bit depth cannot be read. The\n" + \
                           "first calibration logs the white level it actually used plus the observed pixel min/max."

    CB_LOWER_MARGIN_LABEL = "How far the darkest material in the image sits above pure black, as a fraction\n" + \
                            "of the full brightness range (0 = at black; the default 0.15 holds it at 15%\n" + \
                            "brightness). Calibration aims the histogram's dark edge at this level and accepts\n" + \
                            "a wide band around it, since the analysis rescales images. Together the two\n" + \
                            "margins place the whole image: brightness centers it, contrast stretches it to fit."

    CB_UPPER_MARGIN_LABEL = "How far the brightest material in the image sits below pure white, as a fraction\n" + \
                            "of the full brightness range (0 = at white; the default 0.20 holds it at 80%\n" + \
                            "brightness). Larger values give a grayer image with brightness in reserve, so\n" + \
                            "material that darkens as milling proceeds stays measurable. Calibration never\n" + \
                            "pushes past the Max White Clip or Max Black Clip limits."

    CB_MAX_WHITE_CLIP_FRACTION_LABEL = "The maximum acceptable fraction of pixels clipped at the ceiling (white).\n" + \
                                       "Keep this tight: white saturation flattens exactly the bright texture the\n" + \
                                       "analysis measures. Raise it only to deliberately allow clipping."

    CB_MAX_BLACK_CLIP_FRACTION_LABEL = "The maximum acceptable fraction of pixels clipped at the floor (black).\n" + \
                                       "May be looser than the white limit: black pixels are background the\n" + \
                                       "analysis removes anyway."

    CB_MIN_BOUND_LABEL = "The lower clamp on normalized detector contrast/brightness (C/B) values (0-1).\n" + \
                         "Calibration never sets C/B below this value."

    CB_MAX_BOUND_LABEL = "The upper clamp on normalized detector contrast/brightness (C/B) values (0-1).\n" + \
                         "Calibration never sets C/B above this value."

    CB_MAX_ITERATIONS_LABEL = "The measurement budget for one calibration - the total number of RTM measurements\n" + \
                              "(including the final verification) taken before locking at the best setting reached.\n" + \
                              "Calibration exits early on acceptance; a typical run uses well under the budget."

    CB_SETTLE_SECONDS_LABEL = "The minimum time to wait after each contrast/brightness change before re-imaging.\n" + \
                              "One RTM frame period is always allowed even if this is set lower, so that a\n" + \
                              "measurement can never read a frame captured before the change landed.\n" + \
                              "Increase this if your RTM frames are slow to form after a change."

    CB_FRAMES_PER_MEASUREMENT_LABEL = "The number of RTM frames pooled for the accept/verify measurements (noise control).\n" + \
                                      "Search measurements always use a single frame, so calibration stays fast;\n" + \
                                      "raise this if calibration accepts settings that look wrong on inspection."


class MainWindowStyles:

    @staticmethod
    def window() -> str:
        return f"""
            QMainWindow {{
                background-color: {StyleColors.MAIN_BG}
            }}
        """


class DialogStyles:

    @staticmethod
    def modal() -> str:
        return f"""
            QDialog {{
                background-color: {StyleColors.MAIN_BG};
            }}
        """


class LabelStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                color: {StyleColors.TEXT_PRIMARY};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_LARGE};
            }}
        """
    
    @staticmethod
    def settings() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                color: {StyleColors.TEXT_PRIMARY};
                margin-left: {StyleDimensions.MARGIN};
            }}
            QLabel:disabled {{
                color: {StyleColors.TEXT_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_LARGE};
            }}
        """

    @staticmethod
    def result_match() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                font-weight: bold;
                color: "#38003c";
                background-color: {StyleColors.RESULT_MATCH};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                margin-top: {StyleDimensions.RESULT_LABEL_MARGIN};
                margin-bottom: {StyleDimensions.RESULT_LABEL_MARGIN};
                padding-left: {StyleDimensions.RESULT_LABEL_HPAD};
                padding-right: {StyleDimensions.RESULT_LABEL_HPAD};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_LARGE};
            }}
        """
    
    @staticmethod
    def result_label() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                color: {StyleColors.TEXT_PRIMARY};
                margin-top: {StyleDimensions.RESULT_LABEL_MARGIN};
                margin-bottom: {StyleDimensions.RESULT_LABEL_MARGIN};
                padding-left: {StyleDimensions.RESULT_LABEL_HPAD};
                padding-right: {StyleDimensions.RESULT_LABEL_HPAD};
            }}
        """
    
    @staticmethod
    def result_default() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                font-weight: bold;
                color: {StyleColors.TEXT_PRIMARY};
                margin-top: {StyleDimensions.RESULT_LABEL_MARGIN};
                margin-bottom: {StyleDimensions.RESULT_LABEL_MARGIN};
                padding-left: {StyleDimensions.RESULT_LABEL_HPAD};
                padding-right: {StyleDimensions.RESULT_LABEL_HPAD};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_LARGE};
            }}
        """
    
    @staticmethod
    def status_bar() -> str:
        return f"""
            QLabel {{
                font-size: {StyleDimensions.FONT_SIZE_LARGE};
                color: {StyleColors.TEXT_PRIMARY};
                margin-left: {StyleDimensions.MARGIN};
                padding-left: {StyleDimensions.PADDING};
            }}
        """


class GroupBoxStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QGroupBox {{
                /* border: 1px solid {StyleColors.INPUT_BORDER}; */
                border-radius: {StyleDimensions.BORDER_RADIUS_LARGE};
                background-color: {StyleColors.GROUPBOX_BG};
                margin-top: {StyleDimensions.MARGIN};
                margin-left: {StyleDimensions.MARGIN};
                margin-right: {StyleDimensions.MARGIN};
                margin-bottom: {StyleDimensions.MARGIN};
                padding-top: {StyleDimensions.PADDING};
                padding-left: {StyleDimensions.PADDING};
                padding-right: {StyleDimensions.PADDING};
                padding-bottom: {StyleDimensions.PADDING};
            }}
        """

    @staticmethod
    def with_title() -> str:
        return f"""
            QGroupBox {{
                /* border: 1px solid {StyleColors.INPUT_BORDER}; */
                border-radius: {StyleDimensions.BORDER_RADIUS_LARGE};
                background-color: {StyleColors.GROUPBOX_BG};
                margin-top: {StyleDimensions.MARGIN};
                margin-left: {StyleDimensions.MARGIN};
                margin-right: {StyleDimensions.MARGIN};
                margin-bottom: {StyleDimensions.MARGIN};
                padding-top: 30px;
                padding-left: {StyleDimensions.PADDING};
                padding-right: {StyleDimensions.PADDING};
                padding-bottom: {StyleDimensions.PADDING};
                font-weight: bold;
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                color: {StyleColors.TEXT_PRIMARY};
            }}
            QGroupBox::title {{
                subcontrol-origin: padding;
                subcontrol-position: top left;
                left: {StyleDimensions.MARGIN};
                margin-top: 4px;
                padding: 0 10px;
                background-color: {StyleColors.GROUPBOX_BG};
            }}
        """
    
    @staticmethod
    def plot() -> str:
        return f"""
            QGroupBox {{
                border: none;
                border-radius: {StyleDimensions.BORDER_RADIUS_LARGE};
                background-color: {StyleColors.GROUPBOX_BG};
                margin-top: {StyleDimensions.MARGIN};
                margin-left: {StyleDimensions.MARGIN};
                margin-right: {StyleDimensions.MARGIN};
                margin-bottom: {StyleDimensions.MARGIN};
                padding-top: {StyleDimensions.PADDING};
                padding-left: {StyleDimensions.PADDING};
                padding-right: {StyleDimensions.PADDING};
                padding-bottom: {StyleDimensions.PADDING};
            }}
        """
    
    @staticmethod
    def settings() -> str:
        return f"""
            QGroupBox {{
                border: 1px solid {StyleColors.INPUT_BORDER};
                border-radius: {StyleDimensions.BORDER_RADIUS_LARGE};
                background-color: {StyleColors.GROUPBOX_BG};
                margin-top: {StyleDimensions.MARGIN};
                margin-left: {StyleDimensions.MARGIN};
                margin-right: {StyleDimensions.MARGIN};
                margin-bottom: {StyleDimensions.MARGIN};
                padding-top: 30px;
                padding-left: {StyleDimensions.PADDING};
                padding-right: {StyleDimensions.PADDING};
                padding-bottom: {StyleDimensions.PADDING};
                font-weight: bold;
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                color: {StyleColors.TEXT_PRIMARY};
            }}
            QGroupBox::title {{
                subcontrol-origin: padding;
                subcontrol-position: top left;
                left: {StyleDimensions.MARGIN};
                margin-top: 4px;
                padding: 0 10px;
                background-color: {StyleColors.GROUPBOX_BG};
            }}
            QGroupBox:disabled {{
                color: {StyleColors.TEXT_DISABLED};
                border: 1px solid {StyleColors.BUTTON_DISABLED};
            }}
        """


class ButtonStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QPushButton {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                margin: {StyleDimensions.MARGIN};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
            QPushButton:hover {{
                background-color: {StyleColors.BUTTON_HOVER};
            }}
            QPushButton:pressed {{
                background-color: {StyleColors.BUTTON_PRESSED};
            }}
            QPushButton:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
                color: {StyleColors.TEXT_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
        """


class DoubleSpinBoxStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QDoubleSpinBox {{
                background-color: {StyleColors.INPUT_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border: 1px solid {StyleColors.INPUT_BORDER};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
            QDoubleSpinBox:focus {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QDoubleSpinBox:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {{
                width: 0px;
                height: 0px;
            }}
            QDoubleSpinBox:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
                color: {StyleColors.TEXT_DISABLED};
                border: 1px solid {StyleColors.BUTTON_DISABLED};
            }}
        """

    @staticmethod
    def auto_adjusted() -> str:
        return f"""
            QDoubleSpinBox {{
                background-color: {StyleColors.INPUT_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border: 1px solid {StyleColors.INPUT_BORDER_AUTO};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
            QDoubleSpinBox:focus {{
                border: 1px solid {StyleColors.INPUT_BORDER_AUTO};
            }}
            QDoubleSpinBox:hover {{
                border: 1px solid {StyleColors.INPUT_BORDER_AUTO};
            }}
            QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {{
                width: 0px;
                height: 0px;
            }}
            QDoubleSpinBox:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
                color: {StyleColors.TEXT_DISABLED};
                border: 1px solid {StyleColors.BUTTON_DISABLED};
            }}
        """


class CheckBoxStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QCheckBox {{
                color: {StyleColors.TEXT_PRIMARY};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                spacing: {StyleDimensions.CHECKBOX_SPACING};
            }}
            QCheckBox::indicator {{
                width: 18px;
                height: 18px;
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                border: 1px solid {StyleColors.INPUT_BORDER};
                background-color: {StyleColors.INPUT_BG};
            }}
            QCheckBox::indicator:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox::indicator:checked {{
                background-color: {StyleColors.BUTTON_HOVER};
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox:disabled {{
                color: {StyleColors.TEXT_DISABLED};
            }}
            QCheckBox::indicator:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
        """
    
    @staticmethod
    def result_checkbox() -> str:
        return f"""
            QCheckBox {{
                color: {StyleColors.TEXT_PRIMARY};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                spacing: {StyleDimensions.CHECKBOX_SPACING};
                margin-top: {StyleDimensions.RESULT_LABEL_MARGIN};
                margin-bottom: {StyleDimensions.RESULT_LABEL_MARGIN};
            }}
            QCheckBox::indicator {{
                width: 18px;
                height: 18px;
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                border: 1px solid {StyleColors.INPUT_BORDER};
                background-color: {StyleColors.INPUT_BG};
            }}
            QCheckBox::indicator:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox::indicator:checked {{
                background-color: {StyleColors.BUTTON_HOVER};
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox:disabled {{
                color: {StyleColors.TEXT_DISABLED};
            }}
            QCheckBox::indicator:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
        """
    
    @staticmethod
    def settings_dialog() -> str:
        return f"""
            QCheckBox {{
                color: {StyleColors.TEXT_PRIMARY};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
            QCheckBox::indicator {{
                width: 18px;
                height: 18px;
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                border: 1px solid {StyleColors.INPUT_BORDER};
                background-color: {StyleColors.INPUT_BG};
            }}
            QCheckBox::indicator:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox::indicator:checked {{
                background-color: {StyleColors.BUTTON_HOVER};
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QCheckBox:disabled {{
                color: {StyleColors.TEXT_DISABLED};
            }}
            QCheckBox::indicator:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
        """


class RadioButtonStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QRadioButton {{
                color: {StyleColors.TEXT_PRIMARY};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
                spacing: {StyleDimensions.CHECKBOX_SPACING};
            }}
            QRadioButton::indicator {{
                width: 18px;
                height: 18px;
                border-radius: 9px;
                border: 1px solid {StyleColors.INPUT_BORDER};
                background-color: {StyleColors.INPUT_BG};
            }}
            QRadioButton::indicator:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QRadioButton::indicator:checked {{
                background-color: {StyleColors.BUTTON_HOVER};
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QRadioButton:disabled {{
                color: {StyleColors.TEXT_DISABLED};
            }}
            QRadioButton::indicator:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
            }}
            QToolTip {{
                background-color: {StyleColors.BUTTON_BG};
                color: {StyleColors.TEXT_PRIMARY};
                /*border: 1px solid #ffffff;*/
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
        """


class ComboBoxStyles:

    # Arrow icon path
    _arrow_path = str(Path(__file__).parent.parent / "script_assets" / "down_arrow_white.png").replace("\\", "/")

    @staticmethod
    def default() -> str:
        return f"""
            QComboBox {{
                background-color: {StyleColors.INPUT_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border: 1px solid {StyleColors.INPUT_BORDER};
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
                padding: {StyleDimensions.PADDING};
                font-size: {StyleDimensions.FONT_SIZE_NORMAL};
            }}
            QComboBox:hover {{
                border: 1px solid {StyleColors.BUTTON_HOVER};
            }}
            QComboBox:disabled {{
                background-color: {StyleColors.BUTTON_DISABLED};
                color: {StyleColors.TEXT_DISABLED};
                border: 1px solid {StyleColors.BUTTON_DISABLED};
            }}
            QComboBox::drop-down {{
                border: none;
                width: 40px;
            }}
            QComboBox::down-arrow {{
                image: url({ComboBoxStyles._arrow_path});
                width: 14px;
                height: 14px;
                border-left: 8px solid transparent;
                border-right: 8px solid transparent;
            }}
            QComboBox QAbstractItemView {{
                background-color: {StyleColors.INPUT_BG};
                color: {StyleColors.TEXT_PRIMARY};
                border: 1px solid {StyleColors.INPUT_BORDER};
                /* border-radius: {StyleDimensions.BORDER_RADIUS_SMALL}; */
                outline: none;
                selection-background-color: transparent;
                selection-color: {StyleColors.TEXT_PRIMARY};
            }}
            QComboBox QAbstractItemView::item {{
                padding: 8px 8px;
                border: 1px solid {StyleColors.INPUT_BORDER};
                outline: none;
            }}
            QComboBox QAbstractItemView::item:hover {{
                padding: 8px 8px;
                background-color: {StyleColors.BUTTON_BG};
                border: 1px solid {StyleColors.INPUT_BORDER};
                /* border-radius: {StyleDimensions.BORDER_RADIUS_SMALL}; */
            }}
            QComboBox QAbstractItemView::item:selected {{
                background-color: transparent;
                border: 1px solid {StyleColors.INPUT_BORDER};
                /* border-radius: {StyleDimensions.BORDER_RADIUS_SMALL}; */
            }}
            QComboBox QAbstractItemView::item:selected:hover {{
                background-color: {StyleColors.BUTTON_BG};
                border: 1px solid {StyleColors.INPUT_BORDER};
                /* border-radius: {StyleDimensions.BORDER_RADIUS_SMALL}; */
            }}
        """


class StatusBarStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QStatusBar {{
                background-color: {StyleColors.MAIN_BG};
                border: none;
            }}
            QStatusBar::item {{
                background-color: transparent;
                border: none;
            }}
        """


class ScrollAreaStyles:

    @staticmethod
    def default() -> str:
        return f"""
            QScrollArea {{
                background: transparent;
                border: none;
            }}
            QScrollBar:vertical {{
                background: {StyleColors.INPUT_BG};
                width: 12px;
                margin: 0px;
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
            }}
            QScrollBar::handle:vertical {{
                background: {StyleColors.BUTTON_BG};
                min-height: 24px;
                border-radius: {StyleDimensions.BORDER_RADIUS_SMALL};
            }}
            QScrollBar::handle:vertical:hover {{
                background: {StyleColors.BUTTON_HOVER};
            }}
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
                height: 0px;
            }}
            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {{
                background: transparent;
            }}
        """


class AppStyles:

    Colors = StyleColors
    Dimensions = StyleDimensions
    MainWindow = MainWindowStyles
    GroupBox = GroupBoxStyles
    Label = LabelStyles
    Button = ButtonStyles
    SpinBox = DoubleSpinBoxStyles
    AppText = WindowText
    StatusText = StatusText
    AppToolTips = ToolTips
    CheckBox = CheckBoxStyles
    RadioButton = RadioButtonStyles
    ComboBox = ComboBoxStyles
    Dialog = DialogStyles
    StatusBar = StatusBarStyles
    ScrollArea = ScrollAreaStyles